//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEnrollment
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime EnrolledOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
